; Generated by Axiom Compiler (Decoupled Runtime Architecture)
default rel

; --- Windows kernel32.dll API Imports ---
extern GetProcessHeap
extern HeapAlloc
extern HeapFree
extern GetStdHandle
extern WriteFile
extern ExitProcess

section .data
str_lit_0: db 65, 108, 108, 111, 99, 97, 116, 101, 100, 32, 54, 52, 32, 98, 121, 116, 101, 115, 32, 111, 110, 32, 112, 114, 111, 99, 101, 115, 115, 32, 104, 101, 97, 112, 32, 97, 116, 32, 97, 100, 100, 114, 101, 115, 115, 58, 0
str_lit_1: db 86, 97, 108, 117, 101, 32, 115, 116, 111, 114, 101, 100, 32, 105, 110, 115, 105, 100, 101, 32, 104, 101, 97, 112, 32, 98, 108, 111, 99, 107, 58, 0
str_lit_2: db 83, 117, 99, 99, 101, 115, 115, 102, 117, 108, 108, 121, 32, 112, 117, 114, 103, 101, 100, 32, 104, 101, 97, 112, 32, 97, 108, 108, 111, 99, 97, 116, 105, 111, 110, 33, 0

    ; Axiom Runtime Static Literals
    __axiom_crlf: db 13, 10
    __axiom_str_yes: db 'yes', 13, 10
    __axiom_str_no: db 'no', 13, 10

section .bss
reg_0: resq 1
reg_1: resq 1
reg_2: resq 1
reg_3: resq 1
reg_4: resq 1
reg_5: resq 1
reg_6: resq 1
reg_7: resq 1
reg_8: resq 1
reg_9: resq 1
reg_10: resq 1
reg_11: resq 1
var_buffer_size: resq 8
var_ptr: resq 8

    ; Axiom Runtime Internal State
    __axiom_hHeap: resq 1
    __axiom_hStdOut: resq 1
    __axiom_bytes_written: resq 1
    __axiom_print_buf: resb 64

section .text
global mainCRTStartup

mainCRTStartup:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    ; Initialize Axiom Runtime (heap & stdout handles)
    call __axiom_rt_init
    mov rax, 64
    mov [reg_0], rax
    mov rax, [reg_0]
    mov [var_buffer_size], rax
    mov rax, [var_buffer_size]
    mov [reg_1], rax
    mov rcx, [reg_1]
    sub rsp, 32
    call __axiom_claim
    add rsp, 32
    mov [reg_2], rax
    mov rax, [reg_2]
    mov [var_ptr], rax
    mov rax, 1337
    mov [reg_3], rax
    mov rax, [var_ptr]
    mov [reg_4], rax
    mov rax, [reg_4]
    mov rbx, [reg_3]
    mov [rax], rbx
    lea rax, [str_lit_0]
    mov [reg_5], rax
    mov rcx, [reg_5]
    sub rsp, 32
    call __axiom_print_string
    add rsp, 32
    mov rax, [var_ptr]
    mov [reg_6], rax
    mov rcx, [reg_6]
    sub rsp, 32
    call __axiom_print_int
    add rsp, 32
    lea rax, [str_lit_1]
    mov [reg_7], rax
    mov rcx, [reg_7]
    sub rsp, 32
    call __axiom_print_string
    add rsp, 32
    mov rax, [var_ptr]
    mov [reg_8], rax
    mov rax, [reg_8]
    mov rbx, [rax]
    mov [reg_9], rbx
    mov rcx, [reg_9]
    sub rsp, 32
    call __axiom_print_int
    add rsp, 32
    mov rax, [var_ptr]
    mov [reg_10], rax
    mov rcx, [reg_10]
    sub rsp, 32
    call __axiom_purge
    add rsp, 32
    lea rax, [str_lit_2]
    mov [reg_11], rax
    mov rcx, [reg_11]
    sub rsp, 32
    call __axiom_print_string
    add rsp, 32
    ; Exit process via Windows API
    mov ecx, 0
    call ExitProcess

; ===================================================================
; Axiom Runtime Library - Windows x64 Native Implementation
; Freestanding / Zero C Runtime
; ===================================================================

__axiom_rt_init:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    ; Cache STD_OUTPUT_HANDLE (-11)
    mov ecx, -11
    call GetStdHandle
    mov [__axiom_hStdOut], rax
    ; Cache default Process Heap handle
    call GetProcessHeap
    mov [__axiom_hHeap], rax
    add rsp, 32
    pop rbp
    ret

; __axiom_claim(rcx: size) -> rax: pointer
__axiom_claim:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov r8, rcx
    mov rcx, [__axiom_hHeap]
    mov edx, 8
    call HeapAlloc
    add rsp, 32
    pop rbp
    ret

; __axiom_purge(rcx: pointer)
__axiom_purge:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    test rcx, rcx
    jz .free_done
    mov r8, rcx
    mov rcx, [__axiom_hHeap]
    xor edx, edx
    call HeapFree
.free_done:
    add rsp, 32
    pop rbp
    ret

; __axiom_print_int(rcx: int64)
__axiom_print_int:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov rax, rcx
    lea rdi, [__axiom_print_buf + 31]
    mov byte [rdi], 0
    mov byte [rdi - 1], 10
    mov byte [rdi - 2], 13
    sub rdi, 2
    test rax, rax
    jns .int_pos
    neg rax
    mov r8b, 1
    jmp .int_loop
.int_pos:
    xor r8b, r8b
.int_loop:
    xor edx, edx
    mov rbx, 10
    div rbx
    add dl, '0'
    dec rdi
    mov [rdi], dl
    test rax, rax
    jnz .int_loop
    test r8b, r8b
    jz .int_write
    dec rdi
    mov byte [rdi], '-'
.int_write:
    lea rax, [__axiom_print_buf + 31]
    sub rax, rdi
    mov rcx, [__axiom_hStdOut]
    mov rdx, rdi
    mov r8, rax
    lea r9, [__axiom_bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
    add rsp, 48
    pop rbp
    ret

; __axiom_print_string(rcx: const char*)
__axiom_print_string:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    test rcx, rcx
    jz .str_done
    mov rsi, rcx
    xor r8, r8
.str_len:
    cmp byte [rsi + r8], 0
    je .str_write
    inc r8
    jmp .str_len
.str_write:
    mov rcx, [__axiom_hStdOut]
    mov rdx, rsi
    lea r9, [__axiom_bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
    ; Print CRLF
    mov rcx, [__axiom_hStdOut]
    lea rdx, [__axiom_crlf]
    mov r8, 2
    lea r9, [__axiom_bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
.str_done:
    add rsp, 48
    pop rbp
    ret

; __axiom_print_bool(rcx: bool flag)
__axiom_print_bool:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    test rcx, rcx
    jz .bool_no
    lea rdx, [__axiom_str_yes]
    mov r8, 5
    jmp .bool_print
.bool_no:
    lea rdx, [__axiom_str_no]
    mov r8, 4
.bool_print:
    mov rcx, [__axiom_hStdOut]
    lea r9, [__axiom_bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
    add rsp, 48
    pop rbp
    ret

; __axiom_print_double(xmm0: double)
__axiom_print_double:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    cvttsd2si rcx, xmm0
    call __axiom_print_int
    add rsp, 48
    pop rbp
    ret

