use std::collections::{BTreeMap, BTreeSet};
use std::fs::File;
use std::io::{self, Write};
use crate::core::Type;
use crate::ir::{IRInstruction, IRProgram};
use crate::runtime::RuntimeEmitter;

pub struct Emitter<'a> {
    runtime: &'a dyn RuntimeEmitter,
}

impl<'a> Emitter<'a> {
    pub fn new(runtime: &'a dyn RuntimeEmitter) -> Self {
        Emitter { runtime }
    }

    /// Mode A (True C/C++ style): Emit ONLY the user code to user.asm
    /// user.asm declares 'extern __axiom_claim', 'extern __axiom_purge', etc.
    /// The runtime is assembled separately into runtime.obj and linked!
    pub fn emit_user_code_only(&self, program: &IRProgram, filename: &str) -> io::Result<()> {
        let mut file = File::create(filename)?;
        let (registers, global_vars) = self.collect_global_symbols(program);

        self.emit_user_preamble(&mut file)?;
        self.emit_data_section(&mut file, program)?;
        self.emit_bss_section(&mut file, &registers, &global_vars)?;
        self.emit_user_text_section(&mut file, program)?;

        Ok(())
    }

    /// Mode B (Standalone Runtime Library): Emit ONLY the runtime to runtime.asm
    pub fn emit_runtime_library_only(&self, filename: &str) -> io::Result<()> {
        let mut file = File::create(filename)?;
        writeln!(file, "default rel")?;
        self.runtime.emit_externs(&mut file)?;
        self.runtime.emit_globals(&mut file)?;

        writeln!(file, "section .data")?;
        self.runtime.emit_data(&mut file)?;

        writeln!(file, "section .bss")?;
        self.runtime.emit_bss(&mut file)?;

        writeln!(file, "section .text")?;
        self.runtime.emit_runtime_text(&mut file)?;

        Ok(())
    }

    /// Mode C (Bundled single-file): Emits user code then delegates to runtime emitter
    pub fn emit_bundled_to_file(&self, program: &IRProgram, filename: &str) -> io::Result<()> {
        let mut file = File::create(filename)?;
        let (registers, global_vars) = self.collect_global_symbols(program);

        // 1. Preamble & Externs from runtime
        writeln!(file, "; Generated by Axiom Compiler (Decoupled Runtime Architecture)")?;
        writeln!(file, "default rel")?;
        writeln!(file)?;
        self.runtime.emit_externs(&mut file)?;

        // 2. Data section
        self.emit_data_section(&mut file, program)?;
        self.runtime.emit_data(&mut file)?;

        // 3. BSS section
        self.emit_bss_section(&mut file, &registers, &global_vars)?;
        self.runtime.emit_bss(&mut file)?;

        // 4. User Code Text section
        self.emit_user_text_section(&mut file, program)?;

        // 5. Runtime Routines Text section (cleanly appended from runtime module!)
        self.runtime.emit_runtime_text(&mut file)?;

        Ok(())
    }

    fn emit_user_preamble(&self, file: &mut File) -> io::Result<()> {
        writeln!(file, "; ===================================================================")?;
        writeln!(file, "; Axiom User Program Unit")?;
        writeln!(file, "; Target Runtime: {}", self.runtime.name())?;
        writeln!(file, "; Zero Kernel Instructions in User Emitter!")?;
        writeln!(file, "; ===================================================================")?;
        writeln!(file, "default rel")?;
        writeln!(file)?;

        // User code only imports the clean Axiom Runtime symbols!
        writeln!(file, "; Axiom Runtime Library Interface")?;
        writeln!(file, "extern {}", self.runtime.alloc_symbol())?;
        writeln!(file, "extern {}", self.runtime.free_symbol())?;
        writeln!(file, "extern {}", self.runtime.print_int_symbol())?;
        writeln!(file, "extern {}", self.runtime.print_double_symbol())?;
        writeln!(file, "extern {}", self.runtime.print_string_symbol())?;
        writeln!(file, "extern {}", self.runtime.print_bool_symbol())?;
        writeln!(file, "extern __axiom_rt_init")?;
        writeln!(file, "extern ExitProcess")?;
        writeln!(file)?;

        Ok(())
    }

    fn emit_data_section(&self, file: &mut File, program: &IRProgram) -> io::Result<()> {
        writeln!(file, "section .data")?;
        for (id, s) in program.string_literals.iter().enumerate() {
            let mut bytes: Vec<u8> = s.bytes().collect();
            bytes.push(0);
            let byte_strs: Vec<String> = bytes.iter().map(|b| b.to_string()).collect();
            writeln!(file, "str_lit_{}: db {}", id, byte_strs.join(", "))?;
        }
        writeln!(file)?;
        Ok(())
    }

    fn emit_bss_section(
        &self,
        file: &mut File,
        registers: &BTreeSet<usize>,
        global_vars: &BTreeSet<String>,
    ) -> io::Result<()> {
        writeln!(file, "section .bss")?;
        for reg in registers {
            writeln!(file, "reg_{}: resq 1", reg)?;
        }
        for var in global_vars {
            writeln!(file, "var_{}: resq 8", var)?;
        }
        writeln!(file)?;
        Ok(())
    }

    fn emit_user_text_section(&self, file: &mut File, program: &IRProgram) -> io::Result<()> {
        writeln!(file, "section .text")?;
        writeln!(file, "global mainCRTStartup")?;
        writeln!(file)?;

        for p in &program.procs {
            self.emit_proc(file, p)?;
        }

        // Program entry point
        writeln!(file, "mainCRTStartup:")?;
        writeln!(file, "    push rbp")?;
        writeln!(file, "    mov rbp, rsp")?;
        writeln!(file, "    sub rsp, 48")?;

        // Initialize runtime state (e.g. heap handle caching)
        self.runtime.emit_startup_prologue(file)?;

        // Execute user statements
        for ins in &program.main_instructions {
            self.emit_instruction(file, ins, None)?;
        }

        // Graceful termination through runtime
        self.runtime.emit_exit(file, 0)?;
        writeln!(file)?;

        Ok(())
    }

    fn emit_proc(&self, file: &mut File, proc: &crate::ir::IRProc) -> io::Result<()> {
        writeln!(file, "{}:", proc.name)?;
        writeln!(file, "    push rbp")?;
        writeln!(file, "    mov rbp, rsp")?;

        let mut stack_map: BTreeMap<String, usize> = BTreeMap::new();
        let mut current_offset: usize = 8;

        for (p_name, _) in &proc.params {
            stack_map.insert(format!("var_{}", p_name), current_offset);
            current_offset += 8;
        }

        let (proc_regs, proc_vars) = self.collect_local_symbols(&proc.instructions);
        for v in proc_vars {
            let key = format!("var_{}", v);
            if !stack_map.contains_key(&key) {
                stack_map.insert(key, current_offset);
                current_offset += 8;
            }
        }
        for r in proc_regs {
            let key = format!("reg_{}", r);
            stack_map.insert(key, current_offset);
            current_offset += 8;
        }

        let total_frame = ((current_offset + 32 + 15) & !15).max(48);
        writeln!(file, "    sub rsp, {}", total_frame)?;

        let win64_int_regs = ["rcx", "rdx", "r8", "r9"];
        for (idx, (p_name, p_type)) in proc.params.iter().enumerate() {
            if idx < 4 {
                let offset = stack_map[&format!("var_{}", p_name)];
                if *p_type == Type::Num {
                    writeln!(file, "    movq [rbp - {}], xmm{}", offset, idx)?;
                } else {
                    writeln!(file, "    mov [rbp - {}], {}", offset, win64_int_regs[idx])?;
                }
            }
        }

        for ins in &proc.instructions {
            self.emit_instruction(file, ins, Some(&stack_map))?;
        }

        writeln!(file, "    mov rsp, rbp")?;
        writeln!(file, "    pop rbp")?;
        writeln!(file, "    ret")?;
        writeln!(file)?;
        Ok(())
    }

    fn mem_loc(name: &str, stack_map: Option<&BTreeMap<String, usize>>) -> String {
        if let Some(map) = stack_map {
            if let Some(offset) = map.get(name) {
                return format!("[rbp - {}]", offset);
            }
        }
        format!("[{}]", name)
    }

    fn emit_instruction(
        &self,
        file: &mut File,
        ins: &IRInstruction,
        stack_map: Option<&BTreeMap<String, usize>>,
    ) -> io::Result<()> {
        match ins {
            // Console output: Dispatches to runtime routines
            IRInstruction::Emit { reg, reg_type } => {
                let loc = Self::mem_loc(&format!("reg_{}", reg), stack_map);
                match reg_type {
                    Type::Num => {
                        writeln!(file, "    movq xmm0, {}", loc)?;
                        writeln!(file, "    sub rsp, 32")?;
                        writeln!(file, "    call {}", self.runtime.print_double_symbol())?;
                        writeln!(file, "    add rsp, 32")?;
                    }
                    Type::Int => {
                        writeln!(file, "    mov rcx, {}", loc)?;
                        writeln!(file, "    sub rsp, 32")?;
                        writeln!(file, "    call {}", self.runtime.print_int_symbol())?;
                        writeln!(file, "    add rsp, 32")?;
                    }
                    Type::Flag => {
                        writeln!(file, "    mov rcx, {}", loc)?;
                        writeln!(file, "    sub rsp, 32")?;
                        writeln!(file, "    call {}", self.runtime.print_bool_symbol())?;
                        writeln!(file, "    add rsp, 32")?;
                    }
                    Type::Text => {
                        writeln!(file, "    mov rcx, {}", loc)?;
                        writeln!(file, "    sub rsp, 32")?;
                        writeln!(file, "    call {}", self.runtime.print_string_symbol())?;
                        writeln!(file, "    add rsp, 32")?;
                    }
                    _ => {
                        writeln!(file, "    mov rcx, {}", loc)?;
                        writeln!(file, "    sub rsp, 32")?;
                        writeln!(file, "    call {}", self.runtime.print_int_symbol())?;
                        writeln!(file, "    add rsp, 32")?;
                    }
                }
            }

            IRInstruction::LoadFloatConst { dest, val } => {
                let bits = val.to_bits();
                let loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, 0x{:x}", bits)?;
                writeln!(file, "    mov {}, rax", loc)?;
            }
            IRInstruction::LoadIntConst { dest, val } => {
                let loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", val)?;
                writeln!(file, "    mov {}, rax", loc)?;
            }
            IRInstruction::LoadStringConst { dest, str_id } => {
                let loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    lea rax, [str_lit_{}]", str_id)?;
                writeln!(file, "    mov {}, rax", loc)?;
            }
            IRInstruction::LoadBoolConst { dest, val } => {
                let loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", if *val { 1 } else { 0 })?;
                writeln!(file, "    mov {}, rax", loc)?;
            }
            IRInstruction::LoadVar { dest, name } => {
                let var_loc = Self::mem_loc(&format!("var_{}", name), stack_map);
                let reg_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", var_loc)?;
                writeln!(file, "    mov {}, rax", reg_loc)?;
            }
            IRInstruction::StoreVar { name, src } => {
                let reg_loc = Self::mem_loc(&format!("reg_{}", src), stack_map);
                let var_loc = Self::mem_loc(&format!("var_{}", name), stack_map);
                writeln!(file, "    mov rax, {}", reg_loc)?;
                writeln!(file, "    mov {}, rax", var_loc)?;
            }
            IRInstruction::Add { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    addsd xmm0, xmm1")?;
                    writeln!(file, "    movq {}, xmm0", d)?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    add rax, {}", s2)?;
                    writeln!(file, "    mov {}, rax", d)?;
                }
            }
            IRInstruction::Sub { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    subsd xmm0, xmm1")?;
                    writeln!(file, "    movq {}, xmm0", d)?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    sub rax, {}", s2)?;
                    writeln!(file, "    mov {}, rax", d)?;
                }
            }
            IRInstruction::Mul { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    mulsd xmm0, xmm1")?;
                    writeln!(file, "    movq {}, xmm0", d)?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    imul rax, {}", s2)?;
                    writeln!(file, "    mov {}, rax", d)?;
                }
            }
            IRInstruction::Div { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    divsd xmm0, xmm1")?;
                    writeln!(file, "    movq {}, xmm0", d)?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cqo")?;
                    writeln!(file, "    mov rbx, {}", s2)?;
                    writeln!(file, "    idiv rbx")?;
                    writeln!(file, "    mov {}, rax", d)?;
                }
            }
            IRInstruction::Mod { dest, src1, src2 } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", s1)?;
                writeln!(file, "    cqo")?;
                writeln!(file, "    mov rbx, {}", s2)?;
                writeln!(file, "    idiv rbx")?;
                writeln!(file, "    mov {}, rdx", d)?;
            }
            IRInstruction::CmpEq { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm0, xmm1")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                }
                writeln!(file, "    sete al")?;
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpNeq { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm0, xmm1")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                }
                writeln!(file, "    setne al")?;
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpLt { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm1, xmm0")?;
                    writeln!(file, "    seta al")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                    writeln!(file, "    setl al")?;
                }
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpLte { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm1, xmm0")?;
                    writeln!(file, "    setae al")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                    writeln!(file, "    setle al")?;
                }
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpGt { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm0, xmm1")?;
                    writeln!(file, "    seta al")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                    writeln!(file, "    setg al")?;
                }
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpGte { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm0, xmm1")?;
                    writeln!(file, "    setae al")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                    writeln!(file, "    setge al")?;
                }
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::LogAnd { dest, src1, src2 } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", s1)?;
                writeln!(file, "    and rax, {}", s2)?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::LogOr { dest, src1, src2 } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", s1)?;
                writeln!(file, "    or rax, {}", s2)?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::LogNot { dest, src } => {
                let s = Self::mem_loc(&format!("reg_{}", src), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", s)?;
                writeln!(file, "    test rax, rax")?;
                writeln!(file, "    sete al")?;
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::Label(label) => {
                writeln!(file, "{}:", label)?;
            }
            IRInstruction::Jump(label) => {
                writeln!(file, "    jmp {}", label)?;
            }
            IRInstruction::JumpIfFalse { cond_reg, label } => {
                let cond_loc = Self::mem_loc(&format!("reg_{}", cond_reg), stack_map);
                writeln!(file, "    mov rax, {}", cond_loc)?;
                writeln!(file, "    test rax, rax")?;
                writeln!(file, "    jz {}", label)?;
            }
            IRInstruction::Call { dest, name, args } => {
                // "claim" and "purge" are ordinary calls at the IR level; the
                // emitter is the layer that knows they're backed by the
                // runtime library rather than a user/proc label, so it's
                // where their call targets get resolved to the runtime's
                // actual (possibly mangled) symbol names.
                let call_target: &str = match name.as_str() {
                    "claim" => self.runtime.alloc_symbol(),
                    "purge" => self.runtime.free_symbol(),
                    _ => name,
                };

                let win64_int_regs = ["rcx", "rdx", "r8", "r9"];
                for (idx, arg_reg) in args.iter().enumerate() {
                    if idx < 4 {
                        let arg_loc = Self::mem_loc(&format!("reg_{}", arg_reg), stack_map);
                        writeln!(file, "    mov {}, {}", win64_int_regs[idx], arg_loc)?;
                    }
                }
                writeln!(file, "    sub rsp, 32")?;
                writeln!(file, "    call {}", call_target)?;
                writeln!(file, "    add rsp, 32")?;
                if let Some(d) = dest {
                    let d_loc = Self::mem_loc(&format!("reg_{}", d), stack_map);
                    writeln!(file, "    mov {}, rax", d_loc)?;
                }
            }
            IRInstruction::Yield(reg) => {
                if let Some(r) = reg {
                    let r_loc = Self::mem_loc(&format!("reg_{}", r), stack_map);
                    writeln!(file, "    mov rax, {}", r_loc)?;
                }
                writeln!(file, "    mov rsp, rbp")?;
                writeln!(file, "    pop rbp")?;
                writeln!(file, "    ret")?;
            }
            IRInstruction::ComputeAddr { dest, var_name } => {
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if let Some(map) = stack_map {
                    if let Some(offset) = map.get(&format!("var_{}", var_name)) {
                        writeln!(file, "    lea rax, [rbp - {}]", offset)?;
                        writeln!(file, "    mov {}, rax", d_loc)?;
                        return Ok(());
                    }
                }
                writeln!(file, "    lea rax, [var_{}]", var_name)?;
                writeln!(file, "    mov {}, rax", d_loc)?;
            }
            IRInstruction::LoadDeref { dest, ptr_reg } => {
                let p_loc = Self::mem_loc(&format!("reg_{}", ptr_reg), stack_map);
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", p_loc)?;
                writeln!(file, "    mov rbx, [rax]")?;
                writeln!(file, "    mov {}, rbx", d_loc)?;
            }
            IRInstruction::StoreDeref { ptr_reg, val_reg } => {
                let p_loc = Self::mem_loc(&format!("reg_{}", ptr_reg), stack_map);
                let v_loc = Self::mem_loc(&format!("reg_{}", val_reg), stack_map);
                writeln!(file, "    mov rax, {}", p_loc)?;
                writeln!(file, "    mov rbx, {}", v_loc)?;
                writeln!(file, "    mov [rax], rbx")?;
            }
            IRInstruction::ComputeFieldAddr { dest, base_reg, byte_offset } => {
                let b_loc = Self::mem_loc(&format!("reg_{}", base_reg), stack_map);
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", b_loc)?;
                writeln!(file, "    add rax, {}", byte_offset)?;
                writeln!(file, "    mov {}, rax", d_loc)?;
            }
            IRInstruction::ComputeIndexAddr { dest, base_reg, index_reg, elem_size } => {
                let b_loc = Self::mem_loc(&format!("reg_{}", base_reg), stack_map);
                let i_loc = Self::mem_loc(&format!("reg_{}", index_reg), stack_map);
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", b_loc)?;
                writeln!(file, "    mov rbx, {}", i_loc)?;
                writeln!(file, "    imul rbx, {}", elem_size)?;
                writeln!(file, "    add rax, rbx")?;
                writeln!(file, "    mov {}, rax", d_loc)?;
            }
        }
        Ok(())
    }

    fn collect_global_symbols(&self, program: &IRProgram) -> (BTreeSet<usize>, BTreeSet<String>) {
        let mut registers = BTreeSet::new();
        let mut variables = BTreeSet::new();
        self.inspect_instructions(&program.main_instructions, &mut registers, &mut variables);
        (registers, variables)
    }

    fn collect_local_symbols(&self, instructions: &[IRInstruction]) -> (BTreeSet<usize>, BTreeSet<String>) {
        let mut registers = BTreeSet::new();
        let mut variables = BTreeSet::new();
        self.inspect_instructions(instructions, &mut registers, &mut variables);
        (registers, variables)
    }

    fn inspect_instructions(
        &self,
        instructions: &[IRInstruction],
        registers: &mut BTreeSet<usize>,
        variables: &mut BTreeSet<String>,
    ) {
        for ins in instructions {
            match ins {
                IRInstruction::LoadFloatConst { dest, .. }
                | IRInstruction::LoadIntConst { dest, .. }
                | IRInstruction::LoadStringConst { dest, .. }
                | IRInstruction::LoadBoolConst { dest, .. } => {
                    registers.insert(*dest);
                }
                IRInstruction::LoadVar { dest, name } => {
                    registers.insert(*dest);
                    variables.insert(name.clone());
                }
                IRInstruction::StoreVar { name, src } => {
                    registers.insert(*src);
                    variables.insert(name.clone());
                }
                IRInstruction::Add { dest, src1, src2, .. }
                | IRInstruction::Sub { dest, src1, src2, .. }
                | IRInstruction::Mul { dest, src1, src2, .. }
                | IRInstruction::Div { dest, src1, src2, .. }
                | IRInstruction::CmpEq { dest, src1, src2, .. }
                | IRInstruction::CmpNeq { dest, src1, src2, .. }
                | IRInstruction::CmpLt { dest, src1, src2, .. }
                | IRInstruction::CmpLte { dest, src1, src2, .. }
                | IRInstruction::CmpGt { dest, src1, src2, .. }
                | IRInstruction::CmpGte { dest, src1, src2, .. }
                | IRInstruction::LogAnd { dest, src1, src2 }
                | IRInstruction::LogOr { dest, src1, src2 }
                | IRInstruction::Mod { dest, src1, src2 } => {
                    registers.insert(*dest);
                    registers.insert(*src1);
                    registers.insert(*src2);
                }
                IRInstruction::LogNot { dest, src } => {
                    registers.insert(*dest);
                    registers.insert(*src);
                }
                IRInstruction::Emit { reg, .. } => {
                    registers.insert(*reg);
                }
                IRInstruction::JumpIfFalse { cond_reg, .. } => {
                    registers.insert(*cond_reg);
                }
                IRInstruction::Call { dest, args, .. } => {
                    if let Some(d) = dest {
                        registers.insert(*d);
                    }
                    for a in args {
                        registers.insert(*a);
                    }
                }
                IRInstruction::Yield(reg) => {
                    if let Some(r) = reg {
                        registers.insert(*r);
                    }
                }
                IRInstruction::ComputeAddr { dest, var_name } => {
                    registers.insert(*dest);
                    variables.insert(var_name.clone());
                }
                IRInstruction::LoadDeref { dest, ptr_reg } => {
                    registers.insert(*dest);
                    registers.insert(*ptr_reg);
                }
                IRInstruction::StoreDeref { ptr_reg, val_reg } => {
                    registers.insert(*ptr_reg);
                    registers.insert(*val_reg);
                }
                IRInstruction::ComputeFieldAddr { dest, base_reg, .. } => {
                    registers.insert(*dest);
                    registers.insert(*base_reg);
                }
                IRInstruction::ComputeIndexAddr { dest, base_reg, index_reg, .. } => {
                    registers.insert(*dest);
                    registers.insert(*base_reg);
                    registers.insert(*index_reg);
                }
                _ => {}
            }
        }
    }
}